spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: trip-service
          uri: http://localhost:1010
          predicates:
            - Path=/api/v1/trips/**

        - id: notification-service
          uri: http://localhost:1011
          predicates:
            - Path=/api/v1/notification/**

        - id: user-service
          uri: http://localhost:1012
          predicates:
            - Path=/api/v1/users/**

        - id: auth-service
          uri: http://localhost:1013
          predicates:
            - Path=/api/v1/auth/**

        - id: ticket-service
          uri: http://localhost:1014
          predicates:
            - Path=/api/v1/tickets/**

        - id: payment-service
          uri: http://localhost:1015
          predicates:
            - Path=/api/v1/payments/**

        - id: index-service
          uri: http://localhost:1016
          predicates:
            - Path=/api/v1/index/**

        - id: search-service
          uri: http://localhost:1017
          predicates:
            - Path=/api/v1/search/**

        - id: order-service
          uri: http://localhost:1018
          predicates:
            - Path=/api/v1/orders/**

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

server:
  port:
    9090


