version: '3.8'

services:
  postgres:
    image: postgres
    container_name: t-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: t-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: t-rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ default port
      - "15672:15672"  # RabbitMQ Management Plugin (web UI)
    environment:
      RABBITMQ_DEFAULT_USER: melike   # Varsay覺lan kullan覺c覺 ad覺
      RABBITMQ_DEFAULT_PASS: password

